# Private config file for {{ cookiecutter.project_slug }}
# Drop all relevant paths, parameters, etc. here

[contact]
email = "{{ cookiecutter.email }}"

[service_x]
api_key = "MY_API_KEY"

# NOTE: This file must stay ignored by git so that you can safely store your credentials here.
